# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6465d87a7e334fc86e31137ffaec2aa5800ff39b2ae45f2fac6dc841c4df91dd4bd2360864ec2f0da34f6d7cf81999f218f6d3ec1153fad269979c789df687d0

test:
  secret_key_base: f402779c2cda448b4f20ce48bd969f8b779d47549288ad0e8b0bcc53dd0260e18b6201aa02da6486fa414b15587196654ebd6874ec023959fbd4dba1e95e3c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
